require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'
ENV['SWIFT_VERSION'] = '5'
platform :ios, '15'
install! 'cocoapods', :deterministic_uuids => false
production = ENV["PRODUCTION"] == "1"
target 'TestApp' do

  platform :ios, '15'
  # ENV['RCT_NEW_ARCH_ENABLED'] = '0'

  config = use_native_modules!
   # Flags change depending on the env values.
   flags = get_default_flags()
  # pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TestAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'TestApp-tvOS' do

  platform :tvos, '15'

  config = use_native_modules!

   # Flags change depending on the env values.
   flags = get_default_flags()

   use_react_native!(
    :path => config[:reactNativePath],
    # Hermes not yet available on tvOS
    :fabric_enabled => flags[:fabric_enabled],
    # An abosolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  # Hermes not yet available on tvOS
  # use_react_native!(:path => config["reactNativePath"])

  target 'TestApp-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
