export const trackPreRoll = {
  avails: [
    {
      adBreakTrackingEvents: [],
      adMarkerDuration: null,
      ads: [
        {
          adId: '0',
          adParameters: '',
          adProgramDateTime: null,
          adSystem: '2.0',
          adTitle: 'ad-1',
          adVerifications: [],
          companionAds: [],
          creativeId: '98328727222',
          creativeSequence: '1',
          duration: 'PT10.067S',
          durationInSeconds: 10.067,
          extensions: [],
          mediaFiles: {
            mediaFilesList: [],
            mezzanine: '',
          },
          skipOffset: '00:00:05',
          startTime: 'PT0S',
          startTimeInSeconds: 0,
          trackingEvents: [
            {
              beaconUrls: [
                'https://ma0abvngmd.execute-api.us-west-2.amazonaws.com/Development/firstAd',
              ],
              duration: 'PT0S',
              durationInSeconds: 0,
              eventId: '4',
              eventProgramDateTime: null,
              eventType: 'complete',
              startTime: 'PT10.067S',
              startTimeInSeconds: 10.067,
            },
            {
              beaconUrls: [
                'https://ma0abvngmd.execute-api.us-west-2.amazonaws.com/Development/firstAd',
              ],
              duration: 'PT0S',
              durationInSeconds: 0,
              eventId: '3',
              eventProgramDateTime: null,
              eventType: 'thirdQuartile',
              startTime: 'PT7.55025S',
              startTimeInSeconds: 7.55,
            },
            {
              beaconUrls: [''],
              duration: 'PT10.067S',
              durationInSeconds: 10.067,
              eventId: '0',
              eventProgramDateTime: null,
              eventType: 'impression',
              startTime: 'PT0S',
              startTimeInSeconds: 0,
            },
            {
              beaconUrls: [
                'https://ma0abvngmd.execute-api.us-west-2.amazonaws.com/Development/firstAd',
              ],
              duration: 'PT0S',
              durationInSeconds: 0,
              eventId: '1',
              eventProgramDateTime: null,
              eventType: 'firstQuartile',
              startTime: 'PT2.51675S',
              startTimeInSeconds: 2.516,
            },
            {
              beaconUrls: [
                'https://ma0abvngmd.execute-api.us-west-2.amazonaws.com/Development/firstAd',
              ],
              duration: 'PT0S',
              durationInSeconds: 0,
              eventId: '2',
              eventProgramDateTime: null,
              eventType: 'midpoint',
              startTime: 'PT5.0335S',
              startTimeInSeconds: 5.033,
            },
            {
              beaconUrls: [
                'https://ma0abvngmd.execute-api.us-west-2.amazonaws.com/Development/firstAd',
              ],
              duration: 'PT0S',
              durationInSeconds: 0,
              eventId: '0',
              eventProgramDateTime: null,
              eventType: 'start',
              startTime: 'PT0S',
              startTimeInSeconds: 0,
            },
          ],
          vastAdId: '',
        },
      ],
      availId: '0',
      availProgramDateTime: null,
      duration: 'PT10.067S',
      durationInSeconds: 10.067,
      meta: null,
      nonLinearAdsList: [],
      startTime: 'PT0S',
      startTimeInSeconds: 0,
    },
  ],
  dashAvailabilityStartTime: null,
  hlsAnchorMediaSequenceNumber: null,
  nextToken: 'UFQxMC4wNjdTXzIwMjMtMDctMjFUMDc6NDQ6MjUuNDM4NTI5NDgxWl8x',
  nonLinearAvails: [],
};
